# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
variables:
  TF_AUTO_DEPLOY: "true"
  TF_STATE_NAME: default      # The name of the state file used by the GitLab Managed Terraform state backend

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml

.terraform:deploy:
  stage: deploy
  script:
    - sh -c 'while true; do output=$(gitlab-terraform apply 2>&1);       echo "$output" | grep Unauthorized && sleep 15 || (echo "$output" && break); done'
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TF_AUTO_DEPLOY == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

.terraform:build:
  stage: build
  script:
    - sh -c "while true; do output=$(gitlab-terraform plan 2>&1);       echo "$output" | grep Unauthorized && sleep 15 || (echo "$output" && break); done"
    - sh -c "while true; do output=$(gitlab-terraform plan-json 2>&1);  echo "$output" | grep Unauthorized && sleep 15 || (echo "$output" && break); done"
  resource_group: ${TF_STATE_NAME}
  artifacts:
    # The next line, which disables public access to pipeline artifacts, may not be available everywhere.
    # See: https://docs.gitlab.com/ee/ci/yaml/#artifactspublic
    public: false
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

stages:
  - validate
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build
  environment:
    name: $TF_STATE_NAME
    action: prepare

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start
